### ISSUE TITLE
Formulae require at least a URL

### ISSUE THREAD

**Issue by tommasongr** [hashicorp/homebrew-tap#258]
Hi there,

I'm opening this because a user of our Homebrew client ([brewerx.app](https://brewerx.app)) has reported an issue with the repository.

We discovered that the `vagrant` formula is not providing the required `url` for OSs besides Linux. Causing Homebrew to spin up this issue:
```shell
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:306:in 'determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:237:in ' initialize' /opt/homebrew/Library/Homebrew/formulary.rb:492:in 'new'
/opt/homebrew/Library/Homebrew/formulary.rb:492:in 'get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:732 in 'factory'
/opt/homebrew/Library/Taps/paninihouse/homebrew-brewer-cmd/cmd/ brewer-tap-content-info.rb:37:in 'block (2 levels) in brewer_tap_content_info'
/opt/homebrew/Library/Taps/paninihouse/homebrew-brewer-cmd/cmd/ brewer-tap-content-info.rb:36:in 'each'
/opt/homebrew/Library/Taps/paninihouse/homebrew-brewer-cmd/cmd/ brewer-tap-content-info.rb:36:in 'block in brewer_tap_content_info' /opt/homebrew/Library/Homebrew/tap.rb:826:in 'block (2 levels) in each' /opt/homebrew/Library/Homebrew/tap.rb:825 in 'each' /opt/homebrew/Library/Homebrew/tap.rb:825:in 'block in each' /opt/homebrew/Library/Homebrew/tap.rb:824 in 'each' /opt/homebrew/Library/Homebrew/tap.rb:824:in 'each'
/opt/homebrew/Library/Taps/paninihouse/homebrew-brewer-cmd/cmd/ brewer-tap-content-info.rb:34:in 'brewer_tap_content_info' /opt/homebrew/Library/Homebrew/brew.rb:86:in <main>'
```

If you weren't aware, please consider to fix the malformed files.

Thanks

**Comment by kitschpatrol** [comment]
Hi, just chiming in that this is still an issue, and has some knock-on effects... for example, it breaks integrations with brewfile synchronization tools like [homebrew-file](https://homebrew-file.readthedocs.io/en/latest/#).

**Comment by kapral18** [comment]
this is pretty bad it break brew search core functionality like `brew earch --eval-all  --desc <term>`

Looking at contributors for last 6 months

cc: @alvin-huang @CalebAlbers @ashconnor @sujaysamanta 

We would appreciate if you could spare a couple of minutes to look at this.

**Comment by kapral18** [comment]
in the meantime for those who want a managed installation this is a good alternative https://github.com/asdf-community/asdf-hashicorp

**Comment by hkandie** [comment]
In the `vagrant.rb`  that I found the url pointed to a linux image. If you need a quick installation of vagrant just download the dmg file from `https://releases.hashicorp.com/vagrant/2.4.3/` or update the url correctly.

**Comment by kapral18** [comment]
@hkandie no I only installed `vault`, but I get the error mentioning vagrant above every time I run `brew search --eval-all`

**Comment by hossein1376** [comment]
After tapping into `hashicorp/tap` on macOS 26, every brew update shows the following error:

```
Error: Failed to import: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/vagrant.rb
hashicorp/tap/vagrant: formula requires at least a URL
```

I do **not** have Vagrant installed, only terraform.

**Comment by ashconnor** [comment]
Closed via #360
